### ISSUE TITLE
Knihovna jako Composer balík

### ISSUE THREAD

**Issue by janbarasek** [honzaskypala/osloveni#3]
Zdravím,

moc se mi líbí tato knihovna a rád bych ji používal jako hotový balíček pro Composer. Určitě se najde i mnoho dalších vývojářů, kteří to ocení.

Navrhuji, že z tohoto repositáře vytvořím forknutou verzi, která bude tuto knihovnu implementovat a definovat rozhraní pro veřejně dostupný Composer balík.

Mohu poté, prosím, se svolením poslat pull request a do README napsat pokyny, jak balík přidat jako závislost nainstalovat?

Moc děkuji. :)

**Comment by honzaskypala** [comment]
Nevím, jestli je to ještě aktuální, ale pokud máte stále zájem, tak určitě můžete.
