### ISSUE TITLE
PHP not working as expected for words.txt

### ISSUE THREAD

**Issue by parisek** [honzaskypala/osloveni#4]
Hello,

I tried your script on your training data and it's not working as expected, also attached quick test for debug

```
Notice: Uninitialized string offset: 6 in test.php on line 499
Warning: A non-numeric value encountered in test.php on line 499
```

[log.txt](https://github.com/honzaskypala/osloveni/files/9573478/log.txt)
[test.php.txt](https://github.com/honzaskypala/osloveni/files/9573512/test.php.txt)
[words.csv](https://github.com/honzaskypala/osloveni/files/9573513/words.csv)

Thank you

**Comment by honzaskypala** [comment]
Fixed now, thank you for reporting the issue.

**Comment by parisek** [comment]
Thank you for quick fix
